baseURL = "https://zahkthar.github.io/"
title = "Zahkthar"
theme = "erblog"
paginate = 3
languageCode = "en"
DefaultContentLanguage = "fr"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"


[params]
    author = "Zahkthar"
    logo = "https://i.ibb.co/kG74Q7F/Logo-Zahkthar.png"
    favicon = "https://i.ibb.co/kG74Q7F/Logo-Zahkthar.png"
    portrait = "https://i.ibb.co/kG74Q7F/Logo-Zahkthar.png"
    bio = """
    
    Sortant d'un BTS en électronique, actuellement étudiant en Licence d'Informatique et passionné d'informatique et d'électronique, je publie ici "régulièrement" des articles résumant des principes d'électronique et plus tard de programmation appliquée à l'embarqué.
    
    """
    copyright = "Copyright © 2022, Zahkthar; tous droits réservés."


[[menu.main]]
    identifier = "about"
    name = "A propos"
    url = "/about/"
    weight = 10

# [[menu.main]]
#     identifier = "zone"
#     name = "Zone"
#     url = "/zone/"
#     weight = 10

[[menu.footer]]
    identifier = "home"
name = "Accueil"
    url = "/"
    weight = 1

[[menu.footer]]
    identifier = "about"
    name = "A propos"
    url = "/about/"
    weight = 2

[taxonomies]
category = "Catégories"
series = "Séries"
tag = "Étiquettes"

[[menu.icon]]
    url = "https://github.com/Zahkthar"
    name = "chevron-right"
    weight = 1

[[menu.icon]]
    url = "https://github.com/Zahkthar"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://www.youtube.com/watch?v=dQw4w9WgXcQ"
    name = "music"
    weight = 3

[[menu.icon]]
    url = "https://github.com/Zahkthar"
    name = "chevron-left"
    weight = 4